
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # (Optional) mount for live-reload during dev:
    # volumes:
    #   - ./:/app
